# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_RESMANAGE) += common/resource_mgr/cjson.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_RESMANAGE) += common/resource_mgr/param_set.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_RESMANAGE) += common/resource_mgr/resourcemanage.o
