# dtb-y += overlay.dtbo

dtb-y += pwm_a.dtbo \
         pwm_b.dtbo \
         pwm_c.dtbo \
         pwm_f.dtbo \
         spdif_a.dtbo \
         uart1.dtbo \
         uart1-with-ctsrts.dtbo \
         uart2.dtbo \
         uart3.dtbo
