# dtb-y += overlay.dtbo

dtb-y += i2c0.dtbo \
         i2c1.dtbo \
         mcp2515.dtbo \
         mcp2515_12mhz.dtbo \
         mcp2515_16mhz.dtbo \
         mcp2517fd.dtbo \
         pwm_a.dtbo \
         pwm_b.dtbo \
         pwm_c.dtbo \
         pwm_f.dtbo \
         spdif_a.dtbo \
         spi0.dtbo \
         uart1.dtbo \
         uart1-with-ctsrts.dtbo \
         uart2.dtbo \
         uart3.dtbo
