# dtb-y += overlay.dtbo

dtb-y += \
	dht11.dtbo \
	hktft32.dtbo \
	i2c0.dtbo \
	i2c1.dtbo \
	i2c2.dtbo \
	ir.dtbo \
	mcp2515.dtbo \
	mcp2515_12mhz.dtbo \
	mcp2515_16mhz.dtbo \
	mcp2517fd.dtbo \
	onewire.dtbo \
	pwm_a.dtbo \
	pwm_b.dtbo \
	pwm_c.dtbo \
	pwm_f.dtbo \
