# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/hdmi_tx_connector/hdmitx/tx20/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/hdmi_tx_connector/hdmitx/tx21/Makefile

