# SPDX-License-Identifier: GPL-2.0-only
# Amlogic symbol helper drivers

MODULE_NAME1 = amlogic-soc-sym_helper
$(MODULE_NAME1)-$(CONFIG_AMLOGIC_SYM_HELPER) = symbols.o
obj-$(CONFIG_AMLOGIC_SYM_HELPER) = $(MODULE_NAME1).o
