# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
ccflags-y += -I$(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDCP_TX) += vout/hdmi_tx_connector/hdcp/hdmitx_hdcp.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDCP_TX) += vout/hdmi_tx_connector/hdcp/hdmitx_hw_hdcp.o
