# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/enhancement/amdolby_vision/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/enhancement/amvecm/Makefile
