# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/connectors/MIPI_DSI/dsi_addons/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/connectors/MIPI_DSI/dsi_ctrl/Makefile

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_MIPI_DSI) += vout/lcd/connectors/MIPI_DSI/dsi_common.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_MIPI_DSI) += vout/lcd/connectors/MIPI_DSI/dsi_debug.o
