# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/dptx_common.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/dptx_DACP.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/dptx_debug.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/dptx_drm.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/dptx_notify.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/dptx_EDID_DisplayID.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/dptx_link_training.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/dptx_reg_op.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/dptx_vmode_mgr.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/dptx_vout_serve.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/dptx_vout.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/dptx_driver.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/dptx_utils.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/eDP_backlight_wrapper.o

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/eDPTX/VENC/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/eDPTX/CLK/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/eDPTX/DPTX_IP/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/eDPTX/PHY/Makefile
