# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_ODROID_CUSTOM_DISPLAY_MODES) += odroid.o
odroid-y := display.o
odroid-$(CONFIG_ODROID_CUSTOM_DISPLAY_MODES_CMDLINE) += display_cmdline.o
odroid-$(CONFIG_ODROID_CUSTOM_DISPLAY_MODES_DEVICETREE) += display_dt.o
odroid-$(CONFIG_ODROID_CUSTOM_DISPLAY_MODES_MODELINE_FILE) += display_file.o
odroid-$(CONFIG_ODROID_CUSTOM_DISPLAY_MODES_DEBUGFS) += odroid_debugfs.o
