# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/common/arch/registers/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/common/arch/clk/Makefile
