# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD) += vout/lcd/lcd_vout.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD) += vout/lcd/lcd_reg.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD) += vout/lcd/lcd_common.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD) += vout/lcd/lcd_notify.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD) += vout/lcd/lcd_debug.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD) += vout/lcd/lcd_unifykey.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD) += vout/lcd/lcd_tcon.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD) += vout/lcd/lcd_tcon_hw.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD) += vout/lcd/lcd_tcon_fw_param.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD) += vout/lcd/lcd_tcon_debug.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD) += vout/lcd/lcd_tcon_pdf.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD) += vout/lcd/lcd_vbyone.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD) += vout/lcd/lcd_drm.o

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/lcd_venc/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/lcd_tv/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/lcd_tablet/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/lcd_clk/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/lcd_phy/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/lcd_extern/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/backlight/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/ambilight/Makefile
