# SPDX-License-Identifier: (GPL-2.0+ OR MIT)


$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/CLK/dptx_clk_if.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/CLK/dptx_clk_t7.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_eDPTX) += vout/eDPTX/CLK/dptx_clk_utils.o

