# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/video_processor/ppmgr/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/video_processor/utils/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/video_processor/videosync/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/video_processor/pic_dev/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/video_processor/video_dev/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/video_processor/ionvideo/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/video_processor/v4lvideo/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/video_processor/video_composer/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/video_processor/videotunnel/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/video_processor/vdetect/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/video_processor/videoqueue/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/video_processor/common/Makefile
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/video_processor/di_process/Makefile
