# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

#
# Makefile for the amlogic video device interface device drivers.
#

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_UTILS) += video_processor/utils/vfutil.o

