/* SPDX-License-Identifier: (GPL-2.0+ OR MIT) */
/*
 * Copyright (c) 2019 Amlogic, Inc. All rights reserved.
 */

#ifndef __S6_CLKC_H
#define __S6_CLKC_H

#define CLKID_GP0_PLL                             0
#define CLKID_HIFI0_PLL                           1
#define CLKID_HIFI1_PLL                           2
#define CLKID_FCLK50M_DIV                         3
#define CLKID_FCLK50M                             4
#define CLKID_FCLK_DIV2_DIV                       5
#define CLKID_FCLK_DIV2                           6
#define CLKID_FCLK_DIV2P5_DIV                     7
#define CLKID_FCLK_DIV2P5                         8
#define CLKID_FCLK_DIV3_DIV                       9
#define CLKID_FCLK_DIV3                           10
#define CLKID_FCLK_DIV4_DIV                       11
#define CLKID_FCLK_DIV4                           12
#define CLKID_FCLK_DIV5_DIV                       13
#define CLKID_FCLK_DIV5                           14
#define CLKID_FCLK_DIV7_DIV                       15
#define CLKID_FCLK_DIV7                           16
#define CLKID_MCLK_PLL                            17
#define CLKID_MCLK_PLL_DIV                        18
#define CLKID_MCLK_PLL_CLK                        19
#define CLKID_MCLK0_MUX                           20
#define CLKID_MCLK0_DIV2_DIV                      21
#define CLKID_MCLK0_DIV2                          22
#define CLKID_MCLK0_DIV_MUX                       23
#define CLKID_MCLK0                               24
#define CLKID_RTC_DUAL_CLKIN                      25
#define CLKID_RTC_DUAL_DIV                        26
#define CLKID_RTC_DUAL_MUX                        27
#define CLKID_RTC_DUAL                            28
#define CLKID_RTC_CLK                             29
#define CLKID_CLK_24M_IN                          30
#define CLKID_CLK_12M_DIV                         31
#define CLKID_CLK_12M                             32
#define CLKID_SAR_ADC_MUX                         33
#define CLKID_SAR_ADC_DIV                         34
#define CLKID_SAR_ADC                             35
#define CLKID_CECB_DUAL_CLKIN                     36
#define CLKID_CECB_DUAL_DIV                       37
#define CLKID_CECB_DUAL_MUX                       38
#define CLKID_CECB_DUAL                           39
#define CLKID_CECB_CLK                            40
#define CLKID_SC_PRE_MUX                          41
#define CLKID_SC_PRE_DIV                          42
#define CLKID_SC_PRE                              43
#define CLKID_SC_DIV                              44
#define CLKID_CDAC_MUX                            45
#define CLKID_CDAC_DIV                            46
#define CLKID_CDAC                                47
#define CLKID_VIDEO_SRC0_MUX                      48
#define CLKID_VIDEO_SRC0_INPUT                    49
#define CLKID_VIDEO_SRC0_DIV                      50
#define CLKID_VIDEO_SRC0                          51
#define CLKID_VIDEO_SRC1_MUX                      52
#define CLKID_VIDEO_SRC1_INPUT                    53
#define CLKID_VIDEO_SRC1_DIV                      54
#define CLKID_VIDEO_SRC1                          55
#define CLKID_VIDEO0_DIV1                         56
#define CLKID_VIDEO0_DIV2_GATE                    57
#define CLKID_VIDEO0_DIV2                         58
#define CLKID_VIDEO0_DIV4_GATE                    59
#define CLKID_VIDEO0_DIV4                         60
#define CLKID_VIDEO0_DIV6_GATE                    61
#define CLKID_VIDEO0_DIV6                         62
#define CLKID_VIDEO0_DIV12_GATE                   63
#define CLKID_VIDEO0_DIV12                        64
#define CLKID_VIDEO2_DIV1                         65
#define CLKID_VIDEO2_DIV2_GATE                    66
#define CLKID_VIDEO2_DIV2                         67
#define CLKID_VIDEO2_DIV4_GATE                    68
#define CLKID_VIDEO2_DIV4                         69
#define CLKID_VIDEO2_DIV6_GATE                    70
#define CLKID_VIDEO2_DIV6                         71
#define CLKID_VIDEO2_DIV12_GATE                   72
#define CLKID_VIDEO2_DIV12                        73
#define CLKID_LCD_AN_MUX                          74
#define CLKID_LCD_AN                              75
#define CLKID_LCD_AN_PH2                          76
#define CLKID_LCD_AN_PH3                          77
#define CLKID_ENCI_MUX                            78
#define CLKID_ENCI                                79
#define CLKID_ENCP_MUX                            80
#define CLKID_ENCP                                81
#define CLKID_ENCL_MUX                            82
#define CLKID_ENCL                                83
#define CLKID_VDAC_MUX                            84
#define CLKID_VDAC                                85
#define CLKID_HDMITX_PIXEL_MUX                    86
#define CLKID_HDMITX_PIXEL                        87
#define CLKID_HDMITX_FE_MUX                       88
#define CLKID_HDMITX_FE                           89
#define CLKID_MALI_0_MUX                          90
#define CLKID_MALI_0_DIV                          91
#define CLKID_MALI_0                              92
#define CLKID_MALI_1_MUX                          93
#define CLKID_MALI_1_DIV                          94
#define CLKID_MALI_1                              95
#define CLKID_MALI                                96
#define CLKID_MALI_STACK_0_MUX                    97
#define CLKID_MALI_STACK_0_DIV                    98
#define CLKID_MALI_STACK_0                        99
#define CLKID_MALI_STACK_1_MUX                    100
#define CLKID_MALI_STACK_1_DIV                    101
#define CLKID_MALI_STACK_1                        102
#define CLKID_MALI_STACK                          103
#define CLKID_VDEC_0_MUX                          104
#define CLKID_VDEC_0_DIV                          105
#define CLKID_VDEC_0                              106
#define CLKID_VDEC_1_MUX                          107
#define CLKID_VDEC_1_DIV                          108
#define CLKID_VDEC_1                              109
#define CLKID_VDEC                                110
#define CLKID_HEVCF_0_MUX                         111
#define CLKID_HEVCF_0_DIV                         112
#define CLKID_HEVCF_0                             113
#define CLKID_HEVCF_1_MUX                         114
#define CLKID_HEVCF_1_DIV                         115
#define CLKID_HEVCF_1                             116
#define CLKID_HEVCF                               117
#define CLKID_VPU_0_MUX                           118
#define CLKID_VPU_0_DIV                           119
#define CLKID_VPU_0                               120
#define CLKID_VPU_1_MUX                           121
#define CLKID_VPU_1_DIV                           122
#define CLKID_VPU_1                               123
#define CLKID_VPU                                 124
#define CLKID_VPU_CLKB_TMP_MUX                    125
#define CLKID_VPU_CLKB_TMP_DIV                    126
#define CLKID_VPU_CLKB_TMP                        127
#define CLKID_VPU_CLKB_DIV                        128
#define CLKID_VPU_CLKB                            129
#define CLKID_VPU_CLKC_0_MUX                      130
#define CLKID_VPU_CLKC_0_DIV                      131
#define CLKID_VPU_CLKC_0                          132
#define CLKID_VPU_CLKC_1_MUX                      133
#define CLKID_VPU_CLKC_1_DIV                      134
#define CLKID_VPU_CLKC_1                          135
#define CLKID_VPU_CLKC                            136
#define CLKID_VAPB_0_MUX                          137
#define CLKID_VAPB_0_DIV                          138
#define CLKID_VAPB_0                              139
#define CLKID_VAPB_1_MUX                          140
#define CLKID_VAPB_1_DIV                          141
#define CLKID_VAPB_1                              142
#define CLKID_VAPB                                143
#define CLKID_GE2D                                144
#define CLKID_DEWARPA_MUX                         145
#define CLKID_DEWARPA_DIV                         146
#define CLKID_DEWARPA                             147
#define CLKID_CMPR_MUX                            148
#define CLKID_CMPR_DIV                            149
#define CLKID_CMPR                                150
#define CLKID_HDMITX_SYS_MUX                      151
#define CLKID_HDMITX_SYS_DIV                      152
#define CLKID_HDMITX_SYS                          153
#define CLKID_HDMITX_PRIF_MUX                     154
#define CLKID_HDMITX_PRIF_DIV                     155
#define CLKID_HDMITX_PRIF                         156
#define CLKID_HDMITX_200M_MUX                     157
#define CLKID_HDMITX_200M_DIV                     158
#define CLKID_HDMITX_200M                         159
#define CLKID_HDMITX_AUD_MUX                      160
#define CLKID_HDMITX_AUD_DIV                      161
#define CLKID_HDMITX_AUD                          162
#define CLKID_PWM_A_MUX                           163
#define CLKID_PWM_A_DIV                           164
#define CLKID_PWM_A                               165
#define CLKID_PWM_B_MUX                           166
#define CLKID_PWM_B_DIV                           167
#define CLKID_PWM_B                               168
#define CLKID_PWM_C_MUX                           169
#define CLKID_PWM_C_DIV                           170
#define CLKID_PWM_C                               171
#define CLKID_PWM_D_MUX                           172
#define CLKID_PWM_D_DIV                           173
#define CLKID_PWM_D                               174
#define CLKID_PWM_E_MUX                           175
#define CLKID_PWM_E_DIV                           176
#define CLKID_PWM_E                               177
#define CLKID_PWM_F_MUX                           178
#define CLKID_PWM_F_DIV                           179
#define CLKID_PWM_F                               180
#define CLKID_PWM_G_MUX                           181
#define CLKID_PWM_G_DIV                           182
#define CLKID_PWM_G                               183
#define CLKID_PWM_H_MUX                           184
#define CLKID_PWM_H_DIV                           185
#define CLKID_PWM_H                               186
#define CLKID_PWM_I_MUX                           187
#define CLKID_PWM_I_DIV                           188
#define CLKID_PWM_I                               189
#define CLKID_PWM_J_MUX                           190
#define CLKID_PWM_J_DIV                           191
#define CLKID_PWM_J                               192
#define CLKID_SPICC0_MUX                          193
#define CLKID_SPICC0_DIV                          194
#define CLKID_SPICC0                              195
#define CLKID_SD_EMMC_A_MUX                       196
#define CLKID_SD_EMMC_A_DIV                       197
#define CLKID_SD_EMMC_A                           198
#define CLKID_SD_EMMC_B_MUX                       199
#define CLKID_SD_EMMC_B_DIV                       200
#define CLKID_SD_EMMC_B                           201
#define CLKID_SD_EMMC_C_MUX                       202
#define CLKID_SD_EMMC_C_DIV                       203
#define CLKID_SD_EMMC_C                           204
#define CLKID_VDIN_MEAS_MUX                       205
#define CLKID_VDIN_MEAS_DIV                       206
#define CLKID_VDIN_MEAS                           207
#define CLKID_VID_LOCK_MUX                        208
#define CLKID_VID_LOCK_DIV                        209
#define CLKID_VID_LOCK                            210
#define CLKID_ETH_CLK_RMII_MUX                    211
#define CLKID_ETH_CLK_RMII_DIV                    212
#define CLKID_ETH_CLK_RMII                        213
#define CLKID_ETH_CLK125M_DIV                     214
#define CLKID_ETH_CLK125M                         215
#define CLKID_TS_DIV                              216
#define CLKID_TS                                  217
#define CLKID_AMFC_MUX                            218
#define CLKID_AMFC_DIV                            219
#define CLKID_AMFC                                220
#define CLKID_CSI2_ADAPT_MUX                      221
#define CLKID_CSI2_ADAPT_DIV                      222
#define CLKID_CSI2_ADAPT                          223
#define CLKID_MIPI_CSI_PHY_0_MUX                  224
#define CLKID_MIPI_CSI_PHY_0_DIV                  225
#define CLKID_MIPI_CSI_PHY_0                      226
#define CLKID_MIPI_CSI_PHY_1_MUX                  227
#define CLKID_MIPI_CSI_PHY_1_DIV                  228
#define CLKID_MIPI_CSI_PHY_1                      229
#define CLKID_MIPI_CSI_PHY                        230
#define CLKID_MIPI_DSI_MEAS_MUX                   231
#define CLKID_MIPI_DSI_MEAS_DIV                   232
#define CLKID_MIPI_DSI_MEAS                       233
#define CLKID_NNA_MUX                             234
#define CLKID_NNA_DIV                             235
#define CLKID_NNA                                 236
#define CLKID_VC9000E_AXI_MUX                     237
#define CLKID_VC9000E_AXI_DIV                     238
#define CLKID_VC9000E_AXI                         239
#define CLKID_VC9000E_CORE_MUX                    240
#define CLKID_VC9000E_CORE_DIV                    241
#define CLKID_VC9000E_CORE                        242
#define CLKID_DSPA_0_MUX                          243
#define CLKID_DSPA_0_DIV                          244
#define CLKID_DSPA_0                              245
#define CLKID_DSPA_1_MUX                          246
#define CLKID_DSPA_1_DIV                          247
#define CLKID_DSPA_1                              248
#define CLKID_DSPA                                249
#define CLKID_PCIE_TL_MUX                         250
#define CLKID_PCIE_TL_DIV                         251
#define CLKID_PCIE_TL                             252
#define CLKID_USB_250M_MUX                        253
#define CLKID_USB_250M_DIV                        254
#define CLKID_USB_250M                            255
#define CLKID_GEN_MUX                             256
#define CLKID_GEN_DIV                             257
#define CLKID_GEN                                 258
#define CLKID_SYS_AM_AXI                          259
#define CLKID_SYS_DOS                             260
#define CLKID_SYS_VC9000E                         261
#define CLKID_SYS_MIPI_DSI                        262
#define CLKID_SYS_ETHPHY                          263
#define CLKID_SYS_AMFC                            264
#define CLKID_SYS_MALI                            265
#define CLKID_SYS_NNA                             266
#define CLKID_SYS_AOCPU                           267
#define CLKID_SYS_AUCPU                           268
#define CLKID_SYS_CEC                             269
#define CLKID_SYS_MIPI_DSI_PHY                    270
#define CLKID_SYS_SD_EMMC_A                       271
#define CLKID_SYS_SD_EMMC_B                       272
#define CLKID_SYS_SD_EMMC_C                       273
#define CLKID_SYS_SMARTCARD                       274
#define CLKID_SYS_ACODEC                          275
#define CLKID_SYS_MSR_CLK                         276
#define CLKID_SYS_IR_CTRL                         277
#define CLKID_SYS_AUDIO                           278
#define CLKID_SYS_ETH                             279
#define CLKID_SYS_UART_A                          280
#define CLKID_SYS_UART_B                          281
#define CLKID_SYS_UART_C                          282
#define CLKID_SYS_UART_D                          283
#define CLKID_SYS_UART_E                          284
#define CLKID_SYS_TS_PLL                          285
#define CLKID_SYS_CSI_DIG_CLKIN                   286
#define CLKID_SYS_GE2D                            287
#define CLKID_SYS_SPICC0                          288
#define CLKID_SYS_PCIE                            289
#define CLKID_SYS_USB                             290
#define CLKID_SYS_PCIE_PHY                        291
#define CLKID_SYS_I2C_M_A                         292
#define CLKID_SYS_I2C_M_B                         293
#define CLKID_SYS_I2C_M_C                         294
#define CLKID_SYS_I2C_M_D                         295
#define CLKID_SYS_I2C_M_E                         296
#define CLKID_SYS_HDMITX_APB                      297
#define CLKID_SYS_I2C_S_A                         298
#define CLKID_SYS_HDMI20_AES                      299
#define CLKID_SYS_MMC_APB                         300
#define CLKID_SYS_CSI2_HOST                       301
#define CLKID_SYS_CSI2_ADAPT                      302
#define CLKID_SYS_CPU_APB                         303
#define CLKID_SYS_DSPA                            304
#define CLKID_SYS_VPU_INTR                        305
#define CLKID_SYS_CSI2_PHY0                       306
#define CLKID_SYS_SAR_ADC                         307
#define CLKID_SYS_PWM_J                           308
#define CLKID_SYS_GIC                             309
#define CLKID_SYS_PWM_I                           310
#define CLKID_SYS_PWM_H                           311
#define CLKID_SYS_PWM_G                           312
#define CLKID_SYS_PWM_F                           313
#define CLKID_SYS_PWM_E                           314
#define CLKID_SYS_PWM_D                           315
#define CLKID_SYS_PWM_C                           316
#define CLKID_SYS_PWM_B                           317
#define CLKID_SYS_PWM_A                           318
#define CLKID_AXI_AO_NIC                          319
#define CLKID_AXI_DEV0_MMC                        320
#define CLKID_AXI_CPU_SRAM                        321

#define NR_CLKS                                   322

#endif /* __S6_CLKC_H */
