/* SPDX-License-Identifier: (GPL-2.0+ OR MIT) */
/*
 * Copyright (c) 2019 Amlogic, Inc. All rights reserved.
 */

#ifndef __S6_CLKC_H
#define __S6_CLKC_H

#define CLKID_GP0_PLL                             0
#define CLKID_HIFI0_PLL                           1
#define CLKID_HIFI1_PLL                           2
#define CLKID_FCLK50M_DIV                         3
#define CLKID_FCLK50M                             4
#define CLKID_FCLK_DIV2_DIV                       5
#define CLKID_FCLK_DIV2                           6
#define CLKID_FCLK_DIV2P5_DIV                     7
#define CLKID_FCLK_DIV2P5                         8
#define CLKID_FCLK_DIV3_DIV                       9
#define CLKID_FCLK_DIV3                           10
#define CLKID_FCLK_DIV4_DIV                       11
#define CLKID_FCLK_DIV4                           12
#define CLKID_FCLK_DIV5_DIV                       13
#define CLKID_FCLK_DIV5                           14
#define CLKID_FCLK_DIV7_DIV                       15
#define CLKID_FCLK_DIV7                           16
#define CLKID_MCLK_PLL                            17
#define CLKID_MCLK_PLL_CLK                        18
#define CLKID_MCLK0_MUX                           19
#define CLKID_MCLK0_DIV                           20
#define CLKID_MCLK0_DIV2                          21
#define CLKID_MCLK0_DIV_MUX                       22
#define CLKID_MCLK0                               23
#define CLKID_RTC_DUAL_CLKIN                      24
#define CLKID_RTC_DUAL_DIV                        25
#define CLKID_RTC_DUAL_MUX                        26
#define CLKID_RTC_DUAL                            27
#define CLKID_RTC_CLK                             28
#define CLKID_CLK_24M_IN                          29
#define CLKID_CLK_12M_DIV                         30
#define CLKID_CLK_12M                             31
#define CLKID_SAR_ADC_MUX                         32
#define CLKID_SAR_ADC_DIV                         33
#define CLKID_SAR_ADC                             34
#define CLKID_CECB_DUAL_CLKIN                     35
#define CLKID_CECB_DUAL_DIV                       36
#define CLKID_CECB_DUAL_MUX                       37
#define CLKID_CECB_DUAL                           38
#define CLKID_CECB_CLK                            39
#define CLKID_SC_PRE_MUX                          40
#define CLKID_SC_PRE_DIV                          41
#define CLKID_SC_PRE                              42
#define CLKID_SC                                  43
#define CLKID_CDAC_MUX                            44
#define CLKID_CDAC_DIV                            45
#define CLKID_CDAC                                46
#define CLKID_VIDEO_SRC0_MUX                      47
#define CLKID_VIDEO_SRC0_INPUT                    48
#define CLKID_VIDEO_SRC0_DIV                      49
#define CLKID_VIDEO_SRC0                          50
#define CLKID_VIDEO_SRC1_MUX                      51
#define CLKID_VIDEO_SRC1_INPUT                    52
#define CLKID_VIDEO_SRC1_DIV                      53
#define CLKID_VIDEO_SRC1                          54
#define CLKID_VIDEO0_DIV1                         55
#define CLKID_VIDEO0_DIV2_GATE                    56
#define CLKID_VIDEO0_DIV2                         57
#define CLKID_VIDEO0_DIV4_GATE                    58
#define CLKID_VIDEO0_DIV4                         59
#define CLKID_VIDEO0_DIV6_GATE                    60
#define CLKID_VIDEO0_DIV6                         61
#define CLKID_VIDEO0_DIV12_GATE                   62
#define CLKID_VIDEO0_DIV12                        63
#define CLKID_VIDEO2_DIV1                         64
#define CLKID_VIDEO2_DIV2_GATE                    65
#define CLKID_VIDEO2_DIV2                         66
#define CLKID_VIDEO2_DIV4_GATE                    67
#define CLKID_VIDEO2_DIV4                         68
#define CLKID_VIDEO2_DIV6_GATE                    69
#define CLKID_VIDEO2_DIV6                         70
#define CLKID_VIDEO2_DIV12_GATE                   71
#define CLKID_VIDEO2_DIV12                        72
#define CLKID_LCD_AN_MUX                          73
#define CLKID_LCD_AN                              74
#define CLKID_LCD_AN_PH2                          75
#define CLKID_LCD_AN_PH3                          76
#define CLKID_ENCI_MUX                            77
#define CLKID_ENCI                                78
#define CLKID_ENCP_MUX                            79
#define CLKID_ENCP                                80
#define CLKID_ENCL_MUX                            81
#define CLKID_ENCL                                82
#define CLKID_VDAC_MUX                            83
#define CLKID_VDAC                                84
#define CLKID_HDMITX_PIXEL_MUX                    85
#define CLKID_HDMITX_PIXEL                        86
#define CLKID_HDMITX_FE_MUX                       87
#define CLKID_HDMITX_FE                           88
#define CLKID_MALI_0_MUX                          89
#define CLKID_MALI_0_DIV                          90
#define CLKID_MALI_0                              91
#define CLKID_MALI_1_MUX                          92
#define CLKID_MALI_1_DIV                          93
#define CLKID_MALI_1                              94
#define CLKID_MALI                                95
#define CLKID_MALI_STACK_0_MUX                    96
#define CLKID_MALI_STACK_0_DIV                    97
#define CLKID_MALI_STACK_0                        98
#define CLKID_MALI_STACK_1_MUX                    99
#define CLKID_MALI_STACK_1_DIV                    100
#define CLKID_MALI_STACK_1                        101
#define CLKID_MALI_STACK                          102
#define CLKID_VDEC_0_MUX                          103
#define CLKID_VDEC_0_DIV                          104
#define CLKID_VDEC_0                              105
#define CLKID_VDEC_1_MUX                          106
#define CLKID_VDEC_1_DIV                          107
#define CLKID_VDEC_1                              108
#define CLKID_VDEC                                109
#define CLKID_HEVCF_0_MUX                         110
#define CLKID_HEVCF_0_DIV                         111
#define CLKID_HEVCF_0                             112
#define CLKID_HEVCF_1_MUX                         113
#define CLKID_HEVCF_1_DIV                         114
#define CLKID_HEVCF_1                             115
#define CLKID_HEVCF                               116
#define CLKID_VPU_0_MUX                           117
#define CLKID_VPU_0_DIV                           118
#define CLKID_VPU_0                               119
#define CLKID_VPU_1_MUX                           120
#define CLKID_VPU_1_DIV                           121
#define CLKID_VPU_1                               122
#define CLKID_VPU                                 123
#define CLKID_VPU_CLKB_TMP_MUX                    124
#define CLKID_VPU_CLKB_TMP_DIV                    125
#define CLKID_VPU_CLKB_TMP                        126
#define CLKID_VPU_CLKB_DIV                        127
#define CLKID_VPU_CLKB                            128
#define CLKID_VPU_CLKC_0_MUX                      129
#define CLKID_VPU_CLKC_0_DIV                      130
#define CLKID_VPU_CLKC_0                          131
#define CLKID_VPU_CLKC_1_MUX                      132
#define CLKID_VPU_CLKC_1_DIV                      133
#define CLKID_VPU_CLKC_1                          134
#define CLKID_VPU_CLKC                            135
#define CLKID_VAPB_0_MUX                          136
#define CLKID_VAPB_0_DIV                          137
#define CLKID_VAPB_0                              138
#define CLKID_VAPB_1_MUX                          139
#define CLKID_VAPB_1_DIV                          140
#define CLKID_VAPB_1                              141
#define CLKID_VAPB                                142
#define CLKID_GE2D                                143
#define CLKID_DEWARPA_MUX                         144
#define CLKID_DEWARPA_DIV                         145
#define CLKID_DEWARPA                             146
#define CLKID_CMPR_MUX                            147
#define CLKID_CMPR_DIV                            148
#define CLKID_CMPR                                149
#define CLKID_HDMITX_SYS_MUX                      150
#define CLKID_HDMITX_SYS_DIV                      151
#define CLKID_HDMITX_SYS                          152
#define CLKID_HDMITX_PRIF_MUX                     153
#define CLKID_HDMITX_PRIF_DIV                     154
#define CLKID_HDMITX_PRIF                         155
#define CLKID_HDMITX_200M_MUX                     156
#define CLKID_HDMITX_200M_DIV                     157
#define CLKID_HDMITX_200M                         158
#define CLKID_HDMITX_AUD_MUX                      159
#define CLKID_HDMITX_AUD_DIV                      160
#define CLKID_HDMITX_AUD                          161
#define CLKID_PWM_A_MUX                           162
#define CLKID_PWM_A_DIV                           163
#define CLKID_PWM_A                               164
#define CLKID_PWM_B_MUX                           165
#define CLKID_PWM_B_DIV                           166
#define CLKID_PWM_B                               167
#define CLKID_PWM_C_MUX                           168
#define CLKID_PWM_C_DIV                           169
#define CLKID_PWM_C                               170
#define CLKID_PWM_D_MUX                           171
#define CLKID_PWM_D_DIV                           172
#define CLKID_PWM_D                               173
#define CLKID_PWM_E_MUX                           174
#define CLKID_PWM_E_DIV                           175
#define CLKID_PWM_E                               176
#define CLKID_PWM_F_MUX                           177
#define CLKID_PWM_F_DIV                           178
#define CLKID_PWM_F                               179
#define CLKID_PWM_G_MUX                           180
#define CLKID_PWM_G_DIV                           181
#define CLKID_PWM_G                               182
#define CLKID_PWM_H_MUX                           183
#define CLKID_PWM_H_DIV                           184
#define CLKID_PWM_H                               185
#define CLKID_PWM_I_MUX                           186
#define CLKID_PWM_I_DIV                           187
#define CLKID_PWM_I                               188
#define CLKID_PWM_J_MUX                           189
#define CLKID_PWM_J_DIV                           190
#define CLKID_PWM_J                               191
#define CLKID_SPICC0_MUX                          192
#define CLKID_SPICC0_DIV                          193
#define CLKID_SPICC0                              194
#define CLKID_SD_EMMC_A_MUX                       195
#define CLKID_SD_EMMC_A_DIV                       196
#define CLKID_SD_EMMC_A                           197
#define CLKID_SD_EMMC_B_MUX                       198
#define CLKID_SD_EMMC_B_DIV                       199
#define CLKID_SD_EMMC_B                           200
#define CLKID_SD_EMMC_C_MUX                       201
#define CLKID_SD_EMMC_C_DIV                       202
#define CLKID_SD_EMMC_C                           203
#define CLKID_VDIN_MEAS_MUX                       204
#define CLKID_VDIN_MEAS_DIV                       205
#define CLKID_VDIN_MEAS                           206
#define CLKID_VID_LOCK_MUX                        207
#define CLKID_VID_LOCK_DIV                        208
#define CLKID_VID_LOCK                            209
#define CLKID_ETH_CLK_RMII_MUX                    210
#define CLKID_ETH_CLK_RMII_DIV                    211
#define CLKID_ETH_CLK_RMII                        212
#define CLKID_ETH_CLK125M_DIV                     213
#define CLKID_ETH_CLK125M                         214
#define CLKID_TS_DIV                              215
#define CLKID_TS                                  216
#define CLKID_AMFC_MUX                            217
#define CLKID_AMFC_DIV                            218
#define CLKID_AMFC                                219
#define CLKID_CSI2_ADAPT_MUX                      220
#define CLKID_CSI2_ADAPT_DIV                      221
#define CLKID_CSI2_ADAPT                          222
#define CLKID_MIPI_CSI_PHY_0_MUX                  223
#define CLKID_MIPI_CSI_PHY_0_DIV                  224
#define CLKID_MIPI_CSI_PHY_0                      225
#define CLKID_MIPI_CSI_PHY_1_MUX                  226
#define CLKID_MIPI_CSI_PHY_1_DIV                  227
#define CLKID_MIPI_CSI_PHY_1                      228
#define CLKID_MIPI_CSI_PHY                        229
#define CLKID_MIPI_DSI_MEAS_MUX                   230
#define CLKID_MIPI_DSI_MEAS_DIV                   231
#define CLKID_MIPI_DSI_MEAS                       232
#define CLKID_NNA_MUX                             233
#define CLKID_NNA_DIV                             234
#define CLKID_NNA                                 235
#define CLKID_VC9000E_AXI_MUX                     236
#define CLKID_VC9000E_AXI_DIV                     237
#define CLKID_VC9000E_AXI                         238
#define CLKID_VC9000E_CORE_MUX                    239
#define CLKID_VC9000E_CORE_DIV                    240
#define CLKID_VC9000E_CORE                        241
#define CLKID_DSPA_0_MUX                          242
#define CLKID_DSPA_0_DIV                          243
#define CLKID_DSPA_0                              244
#define CLKID_DSPA_1_MUX                          245
#define CLKID_DSPA_1_DIV                          246
#define CLKID_DSPA_1                              247
#define CLKID_DSPA                                248
#define CLKID_PCIE_TL_MUX                         249
#define CLKID_PCIE_TL_DIV                         250
#define CLKID_PCIE_TL                             251
#define CLKID_USB_250M_MUX                        252
#define CLKID_USB_250M_DIV                        253
#define CLKID_USB_250M                            254
#define CLKID_GEN_MUX                             255
#define CLKID_GEN_DIV                             256
#define CLKID_GEN                                 257
#define CLKID_SYS_AM_AXI                          258
#define CLKID_SYS_DOS                             259
#define CLKID_SYS_VC9000E                         260
#define CLKID_SYS_MIPI_DSI                        261
#define CLKID_SYS_ETHPHY                          262
#define CLKID_SYS_AMFC                            263
#define CLKID_SYS_MALI                            264
#define CLKID_SYS_NNA                             265
#define CLKID_SYS_AOCPU                           266
#define CLKID_SYS_AUCPU                           267
#define CLKID_SYS_CEC                             268
#define CLKID_SYS_MIPI_DSI_PHY                    269
#define CLKID_SYS_SD_EMMC_A                       270
#define CLKID_SYS_SD_EMMC_B                       271
#define CLKID_SYS_SD_EMMC_C                       272
#define CLKID_SYS_SMARTCARD                       273
#define CLKID_SYS_ACODEC                          274
#define CLKID_SYS_MSR_CLK                         275
#define CLKID_SYS_IR_CTRL                         276
#define CLKID_SYS_AUDIO                           277
#define CLKID_SYS_ETH                             278
#define CLKID_SYS_UART_A                          279
#define CLKID_SYS_UART_B                          280
#define CLKID_SYS_UART_C                          281
#define CLKID_SYS_UART_D                          282
#define CLKID_SYS_UART_E                          283
#define CLKID_SYS_TS_PLL                          284
#define CLKID_SYS_CSI_DIG_CLKIN                   285
#define CLKID_SYS_GE2D                            286
#define CLKID_SYS_SPICC0                          287
#define CLKID_SYS_PCIE                            288
#define CLKID_SYS_USB                             289
#define CLKID_SYS_PCIE_PHY                        290
#define CLKID_SYS_I2C_M_A                         291
#define CLKID_SYS_I2C_M_B                         292
#define CLKID_SYS_I2C_M_C                         293
#define CLKID_SYS_I2C_M_D                         294
#define CLKID_SYS_I2C_M_E                         295
#define CLKID_SYS_I2C_M_F                         296
#define CLKID_SYS_HDMITX_APB                      297
#define CLKID_SYS_I2C_S_A                         298
#define CLKID_SYS_HDMI20_AES                      299
#define CLKID_SYS_MMC_APB                         300
#define CLKID_SYS_CSI2_HOST                       301
#define CLKID_SYS_CSI2_ADAPT                      302
#define CLKID_SYS_CPU_APB                         303
#define CLKID_SYS_DSPA                            304
#define CLKID_SYS_VPU_INTR                        305
#define CLKID_SYS_CSI2_PHY0                       306
#define CLKID_SYS_SAR_ADC                         307
#define CLKID_SYS_PWM_J                           308
#define CLKID_SYS_GIC                             309
#define CLKID_SYS_PWM_I                           310
#define CLKID_SYS_PWM_H                           311
#define CLKID_SYS_PWM_G                           312
#define CLKID_SYS_PWM_F                           313
#define CLKID_SYS_PWM_E                           314
#define CLKID_SYS_PWM_D                           315
#define CLKID_SYS_PWM_C                           316
#define CLKID_SYS_PWM_B                           317
#define CLKID_SYS_PWM_A                           318
#define CLKID_AXI_AO_NIC                          319
#define CLKID_AXI_DEV0_MMC                        320
#define CLKID_AXI_CPU_SRAM                        321

#define NR_CLKS                                   322

#endif /* __S6_CLKC_H */
