# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
ccflags-y += -I$(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/meson_tx_connector/hdmitx/tx21

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDCP_TX_MODERN) += vout/meson_tx_connector/hdcp/hdmitx_hdcp.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDCP_TX_MODERN) += vout/meson_tx_connector/hdcp/hdmitx_hw_hdcp.o
