# SPDX-License-Identifier: GPL-2.0-only
# Amlogic amfc drivers

MODULE_NAME1 = amlogic-soc-amfc
$(MODULE_NAME1)-$(CONFIG_AMLOGIC_AMFC) = amfc.o
obj-$(CONFIG_AMLOGIC_AMFC) = $(MODULE_NAME1).o

obj-$(CONFIG_AMLOGIC_EROFS)       += aml_erofs/
obj-$(CONFIG_AMLOGIC_ZRAM)        += aml_zram/
obj-$(CONFIG_AMLOGIC_F2FS_FS)     += aml_f2fs/
obj-$(CONFIG_AMLOGIC_SYM_HELPER)  += sym_helper/
