# SPDX-License-Identifier: GPL-2.0

$(MODULE_NAME)-$(CONFIG_MESON_USBPHY) += phy_meson_usb/phy-meson-usb-core.o
$(MODULE_NAME)-$(CONFIG_MESON_USBPHY) += phy_meson_usb/phy-meson-aml-usb2-com.o
$(MODULE_NAME)-$(CONFIG_MESON_USBPHY) += phy_meson_usb/phy-meson-usb2-crg-otg.o
$(MODULE_NAME)-$(CONFIG_MESON_USBPHY) += phy_meson_usb/phy-meson-usb2-crg-otg-v2.o
$(MODULE_NAME)-$(CONFIG_MESON_USBPHY) += phy_meson_usb/phy-meson-usb-rtmux-otg.o
$(MODULE_NAME)-$(CONFIG_MESON_USBPHY) += phy_meson_usb/phy-meson-synopsis-usb3-com.o
$(MODULE_NAME)-$(CONFIG_MESON_USBPHY) += phy_meson_usb/phy-meson-aml-usb3-com.o
include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/usb/phy_meson_usb/socs/Makefile
