/* SPDX-License-Identifier: (GPL-2.0+ OR MIT) */
/*
 * Copyright (c) 2019 Amlogic, Inc. All rights reserved.
 */

#ifndef __DPTX_PLATFORM_REG_H__
#define __DPTX_PLATFORM_REG_H__

#define BASE_REG_OFFSET		24
#define ANACTRL_REG_ADDR(reg) \
	((ANACTRL_REG_IDX << BASE_REG_OFFSET) + ((reg) << 2))
#define PWRCTRL_REG_ADDR(reg) \
	((PWRCTRL_REG_IDX << BASE_REG_OFFSET) + ((reg) << 2))
#define RESETCTRL_REG_ADDR(reg) \
	((RESETCTRL_REG_IDX << BASE_REG_OFFSET) + ((reg) << 2))
#define SYSCTRL_REG_ADDR(reg) \
	((SYSCTRL_REG_IDX << BASE_REG_OFFSET) + ((reg) << 2))
#define CLKCTRL_REG_ADDR(reg) \
	((CLKCTRL_REG_IDX << BASE_REG_OFFSET) + ((reg) << 2))
#define VPUCTRL_REG_ADDR(reg) \
	((VPUCTRL_REG_IDX << BASE_REG_OFFSET) + ((reg) << 2))
#define PADCTRL_REG_ADDR(reg) \
	((PADCTRL_REG_IDX << BASE_REG_OFFSET) + ((reg) << 2))

/* CLK_CTRL */
#define CLKCTRL_VID_CLK_CTRL         CLKCTRL_REG_ADDR(0x0030)
#define CLKCTRL_VID_CLK_CTRL2        CLKCTRL_REG_ADDR(0x0031)
#define CLKCTRL_VID_CLK_DIV          CLKCTRL_REG_ADDR(0x0032)
#define CLKCTRL_VIID_CLK_DIV         CLKCTRL_REG_ADDR(0x0033)
#define CLKCTRL_VIID_CLK_CTRL        CLKCTRL_REG_ADDR(0x0034)
#define CLKCTRL_HDMI_CLK_CTRL        CLKCTRL_REG_ADDR(0x0038)

/* VPU_CTRL */
#define VPU_VIU_VENC_MUX_CTRL         VPUCTRL_REG_ADDR(0x271a)
/*
 * TODO: there are two VPU_HDMI_IF modules, so there are also
 * two groups of below registers
 */
#define VPU_HDMI_SETTING              VPUCTRL_REG_ADDR(0x271b)
#define VPU_HDMI_MATRIX_COEF00_01     VPUCTRL_REG_ADDR(0x273a)
#define VPU_HDMI_MATRIX_COEF02_10     VPUCTRL_REG_ADDR(0x273b)
#define VPU_HDMI_MATRIX_COEF11_12     VPUCTRL_REG_ADDR(0x273c)
#define VPU_HDMI_MATRIX_COEF20_21     VPUCTRL_REG_ADDR(0x273d)
#define VPU_HDMI_MATRIX_COEF22        VPUCTRL_REG_ADDR(0x273e)
#define VPU_HDMI_MATRIX_COEF13_14     VPUCTRL_REG_ADDR(0x273f)
#define VPU_HDMI_FMT_CTRL             VPUCTRL_REG_ADDR(0x2743)
#define VPU_HDMI_MATRIX_COEF23_24     VPUCTRL_REG_ADDR(0x2788)
#define VPU_HDMI_MATRIX_COEF15_25     VPUCTRL_REG_ADDR(0x2789)
#define VPU_HDMI_MATRIX_CLIP          VPUCTRL_REG_ADDR(0x278a)
#define VPU_HDMI_MATRIX_OFFSET0_1     VPUCTRL_REG_ADDR(0x278b)
#define VPU_HDMI_MATRIX_OFFSET2       VPUCTRL_REG_ADDR(0x278c)
#define VPU_HDMI_MATRIX_PRE_OFFSET0_1 VPUCTRL_REG_ADDR(0x278d)
#define VPU_HDMI_MATRIX_PRE_OFFSET2   VPUCTRL_REG_ADDR(0x278e)
#define VPU_HDMI_MATRIX_EN_CTRL       VPUCTRL_REG_ADDR(0x278f)
#define VPU_HDMI_DITH_CNTL            VPUCTRL_REG_ADDR(0x27fc)
#endif

