# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

ccflags-y += -I$(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/hdmi_tx_connector

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/esm_hdcp_tx.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_hdcp.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_scdc.o

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_hw.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_dump.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_reg_ops.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_enc_cfg_hw.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_ddc.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_check_sha.o

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX_GXX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_hw_gxbb.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX_GXX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_hw_gxtvbb.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX_GXX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_hw_gxl.o

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_hw_txlx.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_hw_clk.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_hw_g12a.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_hw_sm1.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_hw_tm2.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HDMITX) += vout/hdmi_tx_connector/hdmitx/tx20/hdmitx_hw_sc2.o
