/* SPDX-License-Identifier: (GPL-2.0+ OR MIT) */
/*
 * Copyright (c) 2019 Amlogic, Inc. All rights reserved.
 */

#ifndef __MESON_TX_HW_OPCODE_H
#define __MESON_TX_HW_OPCODE_H

/* hw_cntl cmd type */
#define CMD_TYPE_MASK				(0xFF << 24)
#define CMD_DDC_AUX_OFFSET			(0x10 << 24)
#define CMD_HDCP_OFFSET				(0x11 << 24)
#define CMD_AUX_PKT_OFFSET			(0x12 << 24)
#define CMD_AUX_AUD_OFFSET			(0x13 << 24)
#define CMD_ALLM_OFFSET				(0x14 << 24)
#define CMD_FRL_OFFSET				(0x15 << 24)
#define CMD_DSC_OFFSET				(0x16 << 24)
#define CMD_VRR_OFFSET				(0x17 << 24)
#define CMD_CORE_MISC_OFFSET			(0x18 << 24)
#define CMD_PLATFORM_CNTL_OFFSET		(0x19 << 24)
#define CMD_VPU_CNTL_OFFSET			(0x1a << 24)
#define CMD_MODE_FLOW_MISC_OFFSET		(0x1b << 24)
#define CMD_LINK_TRAINING_OFFSET		(0x1c << 24)
#define CMD_MST_OFFSET				(0x1d << 24)

/* 0x10 DDC */
enum cmd_ddc_aux {
	DDC_PIN_MUX_OP = CMD_DDC_AUX_OFFSET,
	DDC_RESET_EDID,
	DDC_EDID_READ_DATA,
	DDC_GET_CEDST,
	DDC_GLITCH_FILTER_RESET,
	DDC_I2C_RATE,
	DDC_I2C_RESET,
	DDC_SCDC_DIV40_SCRAMB,
};

#define PIN_MUX 0x1

/* 0x11 HDCP */
enum cmd_hdcp {
	HDCP_ESM_RESET = CMD_HDCP_OFFSET,
	HDCP_CLKDIS,
	HDCP_MODE_OP,
	HDCP_DISABLE,
	HDCP_RESET,
	HDCP_GET_AKSV,
	HDCP_GET_BKSV,
	HDCP_GET_AUTH_RESULT,
	/* reset hdcp param for suspend/plugout, not for mode switch */
	HDCP_PARAM_RESET,
	HDCP14_KEY_LOAD,
	/* check hdcp22 support or not by DDC read */
	HDCP22_GET_RX_VER,
	HDCP_REQ_AUTH,
	HDCP_UNUSED,
	/* for hdcp_tx22 ready check on linux platform */
	HDCP_22_PRIVATE_KEY_RDY,
	HDCP_MUX_INIT,
	HDCP_14_LSTORE,
	HDCP_22_LSTORE,
	HDCP14_GET_BCAPS_RP,
	HDCP14_GET_TOPO_INFO,
	HDCP_SET_TOPO_INFO,
	HDCP_GET_TOPO_INFO,
	HDCP14_SAVE_OBS,
};

#define HDCP14_ON	0x1
#define HDCP14_OFF	0x2
#define HDCP22_ON	0x3
#define HDCP22_OFF	0x4

/* 0x12 packet */
enum cmd_aux_pkt {
	AUX_PKT_GET_GCP_CD = CMD_AUX_PKT_OFFSET,
	AUX_PKT_CONFIG_AVMUTE,
	AUX_PKT_GET_AVMUTE_ST,
	AUX_PKT_SET_SPD_INFO,
	AUX_PKT_AVI_CONSTRUCT,
	AUX_PKT_GET_AVI_VIC,
	AUX_PKT_SET_AVI_VIC,
	AUX_PKT_GET_AVI_CS,
	AUX_PKT_SET_AVI_CS,
	AUX_PKT_CONF_AVI_BT2020,
	AUX_PKT_GET_AVI_BT2020,
	AUX_PKT_CONF_AVI_Q01,
	AUX_PKT_CONF_AVI_YQ01,
	AUX_PKT_CONF_AVI_CT,
	AUX_PKT_CONF_AVI_ASPECT,
	AUX_PKT_CONF_AVI_SCAN,
	AUX_PKT_GET_AVI_SCAN,
	AUX_PKT_CLR_AVI,
	AUX_PKT_GET_HDR_ST,
	AUX_PKT_GET_AMDV_ST,
	AUX_PKT_GET_HDR10P_ST,
	AUX_PKT_GET_CUVA_ST,
	AUX_PKT_CLR_DV_VS10_SIG,
	AUX_PKT_SET_VSIF1,
	AUX_PKT_SET_VSIF2,
	AUX_PKT_DIS_VSIF,
	AUX_PKT_SET_DRM,
	AUX_PKT_SET_EMP_CUVA,
	AUX_PKT_SET_EMP_SBTM,
	AUX_PKT_SET_SDP, /* used for setting the Secondary Data Packet */
	AUX_PKT_GET_SDP, /* used for getting the Secondary Data Packet */
	AUX_PKT_SDP_INFO_DUMP
};

#define OFF_AVMUTE		0x0
#define CLR_AVMUTE		0x1
#define SET_AVMUTE		0x2

#define CLR_AVI_BT2020	0
#define SET_AVI_BT2020	1

/* 0x13 audio */
enum cmd_aux_aud {
	AUDIO_RESET = CMD_AUX_AUD_OFFSET,
	AUDIO_ACR_CTRL,
	AUDIO_PREPARE,
	AUDIO_MUTE_OP,
	AUDIO_GET_UBOOT_ST,
};

#define AUDIO_MUTE		0x1
#define AUDIO_UNMUTE	0x2

/* 0x14 ALLM */
enum cmd_allm {
	ALLM_CONFIG = CMD_ALLM_OFFSET,
};

#define ENABLE_ALLM         1
#define DISABLE_ALLM        0

/* 0x15 FRL */
enum cmd_frl {
	FRL_GET_MODE = CMD_FRL_OFFSET,
	FRL_CLR_MODE,
	FRL_GET_RX_READY_ST,
	FRL_DISABLE_WORK,
};

/* 0x16 DSC */
enum cmd_dsc {
	DSC_GET_TX_EN = CMD_DSC_OFFSET,
};

/* 0x17 VRR */
enum cmd_vrr {
	VRR_REGISTER = CMD_VRR_OFFSET,
	QMS_GET_INFO,
};

/* 0x18 core misc */
enum cmd_core_misc {
	CORE_MISC_SUSPEND_RESUME_CNTL = CMD_CORE_MISC_OFFSET,
	CORE_MISC_TMDS_CLK_DIV40,
	CORE_MISC_GET_OUTPUT_ST,
	CORE_MISC_SET_HDMI_DVI_MODE,
	CORE_MISC_GET_HDMI_DVI_MODE,
	CORE_MISC_VP_CMS_CSC,
	CORE_MISC_HW_INIT,
	CORE_MISC_TRIGGER_HPD,
	CORE_MISC_EVENT_PROCESS,
	CORE_MISC_REG_RD_WR,
	CORE_MISC_HDCP_SUSPEND,
	CORE_MISC_HDCP_RESUME,
};

#define HDMITX_EARLY_SUSPEND	0x1
#define HDMITX_LATE_RESUME		0x2

#define HDMI_MODE	0x1
#define DVI_MODE	0x2

/* 0x19 CMD_PLATFORM */
enum cmd_platform {
	/* hpll/clk */
	CMD_PLATFORM_CLK_CNTL_OFFSET = CMD_PLATFORM_CNTL_OFFSET + (0x1 << 16),
	PLATFORM_GET_HPD_GPI_ST,
	PLATFORM_HPD_MUX_OP,
	PLATFORM_DIS_HPLL,
	PLATFORM_ESM_CLK_CTRL,
	PLATFORM_CLK_DIV_RST,
	PLATFORM_HDMI_CLKS_CTRL,
	PLATFORM_GET_CLKMSR,
	PLATFORM_VID_CLK_PARAM_BUILD,

	/* phy */
	CMD_PLATFORM_PHY_CNTL_OFFSET = CMD_PLATFORM_CNTL_OFFSET + (0x2 << 16),
	PLATFORM_PHY_OP = CMD_PLATFORM_PHY_CNTL_OFFSET,
	PLATFORM_RXSENSE,
	PLATFORM_GET_PHY_STAT,
};

#define TMDS_PHY_NONE		0x0
#define TMDS_PHY_ENABLE		0x1
#define TMDS_PHY_DISABLE	0x2

/* 0x1a VPU */
enum cmd_vpu {
	VPU_VIDEO_MUTE_OP = CMD_VPU_CNTL_OFFSET,
	VPU_CONFIG_CSC,
	VPU_CONFIG_CSC_EN,
	VPU_CONFIG_DITHER,
};

#define VIDEO_NONE_OP	0x0
#define VIDEO_MUTE		0x1
#define VIDEO_UNMUTE	0x2

/* set value as COLORSPACE_RGB444, YUV422, YUV444, YUV420 */
#define CSC_Y444_8BIT		0x1
#define CSC_Y422_12BIT		0x2
#define CSC_RGB_8BIT		0x3
#define CSC_UPDATE_AVI_CS	0x10

/* set CSC_ENABLE when DV_STD && Adaptive HDR */
#define CSC_ENABLE		1
#define CSC_DISABLE		0

/* 0x1b mode flow misc */
enum cmd_mode_flow {
	MODE_FLOW_PRIVATE_PLUGOUT_PROCESS = CMD_MODE_FLOW_MISC_OFFSET,
	MODE_FLOW_HPD_IRQ_TOP_HALF,
	MODE_FLOW_PRE_ENABLE_MODE,
	MODE_FLOW_ENABLE_MODE,
	MODE_FLOW_POST_ENABLE_MODE,
	MODE_FLOW_DISABLE_21_WORK,
};

#endif
