# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_RDMA) += common/rdma/rdma_mgr.o

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VSYNC_RDMA) += common/rdma/rdma.o
