# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DPSS_PROCESS) += video_processor/dpss_process/dpss_proc_file.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DPSS_PROCESS) += video_processor/dpss_process/dpss_process.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DPSS_THERMAL) += video_processor/dpss_process/dpss_cooling.o
