# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/vclk_serve/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/vout_serve/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/hdmitx_common/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/hdmitx21/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/hdmitx20/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/cvbs/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/vdac/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/peripheral_lcd/Makefile

include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/dsc/Makefile

