# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TCON) += vout/lcd/connectors/tcon/lcd_tcon.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TCON) += vout/lcd/connectors/tcon/lcd_tcon_hw.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TCON) += vout/lcd/connectors/tcon/lcd_tcon_fw_param.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TCON) += vout/lcd/connectors/tcon/lcd_tcon_debug.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TCON) += vout/lcd/connectors/tcon/lcd_tcon_pdf.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TCON) += vout/lcd/connectors/tcon/lcd_tcon_rdma.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TCON) += vout/lcd/connectors/tcon/lcd_tcon_swpdf.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TCON) += vout/lcd/connectors/tcon/lcd_tcon_vrr.o
